version: "15.37"
name: hrms
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
  redis:
    image: redis:alpine
  frappe:
    image: frappe/bench:latest
    command: >
    bash -c '
    if [ ! -f /workspace/init.sh ]; then
      echo "Creating init.sh script..."
      cat <<EOF > /workspace/init.sh
    #!/bin/bash
    if [ -d "/home/frappe/frappe-bench/apps/frappe" ]; then
      echo "Bench already exists, skipping init"
      cd frappe-bench
      bench start
    else
      echo "Creating new bench..."
    fi
    export PATH="\${NVM_DIR}/versions/node/v\${NODE_VERSION_DEVELOP}/bin/:\${PATH}"
    bench init --skip-redis-config-generation frappe-bench
    cd frappe-bench
    bench set-mariadb-host mariadb
    bench set-redis-cache-host redis:6379
    bench set-redis-queue-host redis:6379
    bench set-redis-socketio-host redis:6379
    sed -i "/redis/d" ./Procfile
    sed -i "/watch/d" ./Procfile
    bench get-app erpnext
    bench get-app hrms
    bench new-site hrms.localhost \
    --force \
    --mariadb-root-password 123 \
    --admin-password admin \
    --no-mariadb-socket
    bench --site hrms.localhost install-app hrms
    bench --site hrms.localhost set-config developer_mode 1
    bench --site hrms.localhost enable-scheduler
    bench --site hrms.localhost clear-cache
    bench use hrms.localhost
    bench start
    EOF
      chmod +x /workspace/init.sh
      fi
      bash /workspace/init.sh'
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8100:8100
      - 9000:9000
volumes:
  mariadb-data:
